[package]
name = "nubila"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
glium = "0.35"
glutin-winit = "0.5.0"
thiserror = "1.0.63"

[[bin]]
name = "nubila"
path = "src/main.rs"
